name: required_env
channels:
  - simpleitk
  - pytorch
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - alabaster=0.7.12
  - anyio=2.2.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - astor=0.8.1
  - astroid=2.5
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - binaryornot=0.4.4
  - black=19.10b0
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2024.2.2
  - cffi=1.14.5
  - chardet=4.0.0
  - charls=2.2.0
  - click=7.1.2
  - cloudpickle=1.1.1
  - colorama=0.4.4
  - comtypes=1.1.9
  - cookiecutter=1.7.2
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask-core=2021.4.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - flake8=3.9.0
  - flit-core=3.6.0
  - freetype=2.10.4
  - future=0.18.2
  - gast=0.2.2
  - giflib=5.2.1
  - google-pasta=0.2.0
  - graphviz=2.38
  - grpcio=1.36.1
  - h5py=2.8.0
  - hdf5=1.8.20
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib_metadata=3.10.0
  - inflection=0.5.1
  - intel-openmp=2021.2.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.3
  - isort=5.8.0
  - jdcal=1.4.1
  - jedi=0.17.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=3.0.13
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.2
  - keyring=22.3.0
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.7
  - libiconv=1.15
  - libopencv=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.1.0
  - libuv=1.44.2
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - locket=0.2.1
  - lxml=4.6.1
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.5.1
  - nibabel=3.2.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.0
  - numpy=1.20.1
  - numpy-base=1.20.1
  - numpydoc=1.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openjpeg=2.3.0
  - openssl=1.1.1l
  - opt_einsum=3.1.0
  - pandoc=2.12
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.2.0
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - pluggy=0.13.1
  - poyo=0.5.0
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py-opencv=3.4.2
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydicom=2.1.2
  - pydocstyle=6.0.0
  - pydot=1.4.1
  - pyflakes=2.2.0
  - pylint=2.7.4
  - pyls-black=0.4.6
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.0
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-slugify=5.0.2
  - python_abi=3.7
  - pytorch-mutex=1.0
  - pytz=2021.1
  - pywavelets=1.1.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinauto=0.6.8
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=2.8.1
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - regex=2021.4.4
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.7
  - scikit-image=0.17.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simpleitk=2.0.2
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.3.0
  - sphinx=1.8.5
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.35.4
  - sympy=1.7.1
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - tensorflow-probability=0.8.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tifffile=2021.4.8
  - tinycss=0.4
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - ujson=4.0.2
  - unidecode=1.2.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - whichcraft=0.6.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - accelerate==0.20.3
    - aenum==3.1.15
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.3
    - asynctest==0.13.0
    - bitsandbytes==0.43.3
    - cachetools==5.5.2
    - category-encoders==2.6.4
    - charset-normalizer==3.3.2
    - construct==2.10.70
    - datasets==2.13.2
    - dill==0.3.6
    - einops==0.6.1
    - filelock==3.12.2
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - gin-config==0.4.0
    - google-auth==2.40.1
    - google-auth-oauthlib==0.4.6
    - grad-cam==1.4.8
    - huggingface-hub==0.16.4
    - imageio-ffmpeg==0.4.9
    - imbalanced-learn==0.12.4
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - joblib==1.3.2
    - lightning-utilities==0.10.1
    - littleutils==0.2.2
    - llvmlite==0.39.1
    - markdown-it-py==2.2.0
    - markupsafe==2.0.1
    - mdurl==0.1.2
    - medpalm==0.1.9
    - multidict==6.0.5
    - multiprocess==0.70.14
    - natsort==8.4.0
    - numba==0.56.4
    - oauthlib==3.2.2
    - oct-converter==0.6.2
    - omegaconf==2.3.0
    - opencv-python==3.4.18.65
    - openpyxl==3.1.3
    - outdated==0.2.2
    - packaging==24.0
    - pandas==1.1.5
    - pandas-flavor==0.2.0
    - patsy==1.0.1
    - pingouin==0.5.3
    - protobuf==3.20.3
    - pyarrow==12.0.1
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pygments==2.17.2
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.4
    - pylibjpeg-openjpeg==1.3.2
    - pynndescent==0.5.13
    - pypdn==1.0.6
    - pyreadr==0.4.3
    - pyreadstat==1.1.3
    - pytorch-lightning==1.9.5
    - pytorch-tabnet==4.0
    - pytorch-tabular==1.0.2
    - requests-oauthlib==2.0.0
    - rich==13.8.1
    - rsa==4.9.1
    - safetensors==0.4.5
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentencepiece==0.2.0
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - timm==0.9.12
    - tokenizers==0.13.3
    - torch==1.12.1
    - torchaudio==0.12.1+cu113
    - torchmetrics==0.11.4
    - torchvision==0.13.1+cu113
    - tqdm==4.66.5
    - transformers==4.30.2
    - ttach==0.0.3
    - typing-extensions==4.7.1
    - umap-learn==0.5.7
    - urllib3==1.26.15
    - werkzeug==2.1.2
    - xarray==0.20.2
    - xgboost==1.6.2
    - xxhash==3.5.0
    - yarl==1.9.4

